FROM {{ .BaseImage }}
#FROM opensuse:latest

MAINTAINER cloudfoundry@suse.example

# Install prerequisites
# Install monit and other dependencies
# Setup syslog
# Enable resolvconf updates # TODO: remove?
# Setup default locale and timezone # TODO: Remove?

RUN useradd -m --comment 'fissile user' vcap && \
    groupadd --system admin && \
    usermod -G admin,audio,cdrom,dialout,floppy,video vcap && \
    zypper ref && zypper -n in vim monit curl nfs-utils tcpdump lsof strace arping2 traceroute htop bind-utils wget libcurl4 bison libxml2 libxslt libyaml-0-2 zip unzip flex psmisc apparmor-utils iptables sysstat rsync quota libaio1 libcap2 cmake ca-certificates debhelper cronie-anacron openssh rsyslog rsyslog-module-relp rsyslog-module-gtls glibc-locale && \

    #apt-get update && \
    #apt-get install vim monit runit curl software-properties-common nfs-common upstart tcpdump lsof strace iputils-arping traceroute htop bind9-host dnsutils wget libcurl3 bison libxml2 libxslt1.1 libyaml-0-2 zip unzip flex psmisc apparmor-utils iptables sysstat rsync quota libaio1 libcap2-bin cmake ca-certificates scsitools mg module-assistant debhelper anacron openssh-client -y && \

    #add-apt-repository ppa:adiscon/v8-stable && \
    #
    #apt-get update && \
    #apt-get install rsyslog rsyslog-relp rsyslog-mmjsonparse rsyslog-gnutls -y && \
    #resolvconf --enable-updates && \ # TODO Needed?

    # TODO: Needed?
    #echo 'LANG=en_US.UTF-8' >> /etc/sysconfig/language && \
    #echo 'LANG="en_US.UTF-8"' > /etc/default/locale && \
    #echo 'UTC' > /etc/timezone && \
    #DEBIAN_FRONTEND=noninteractive locale-gen en_US.UTF-8 && \
    #dpkg-reconfigure -fnoninteractive -pcritical tzdata && \
    #dpkg-reconfigure locales && \

    wget https://github.com/Yelp/dumb-init/releases/download/v1.1.3/dumb-init_1.1.3_amd64 && \
    echo '1af305fc011c72aa899c88fe6576e82f2c7657d8d5212a13583fd2de012e478f  dumb-init_1.1.3_amd64' | sha256sum --check && \
    install dumb-init_1.1.3_amd64 /usr/bin/dumb-init && \
    rm -f dumb-init_1.1.3_amd64 && \
    (useradd --system --user-group --no-create-home syslog || true)
    # usermod -G vcap syslog && \ # TODO: vcap group doesn't exist


    #wget https://github.com/Yelp/dumb-init/releases/download/v1.1.3/dumb-init_1.1.3_amd64.deb && \
    #echo '34995cf69c88311e9475b4d101186b1d5f4d653f222e41c6e5643ff4e6f56f54 *dumb-init_1.1.3_amd64.deb' | sha256sum --check && \
    #dpkg -i dumb-init_*.deb && \
    #rm -f dumb-init_*.deb && \
    #(useradd --system --user-group --no-create-home syslog || true) && \
    #usermod -G vcap syslog && \
    #apt-get autoremove -y && \
    #apt-get clean && \
    #rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ADD monitrc.erb /opt/hcf/monitrc.erb

ADD post-start.sh /opt/hcf/post-start.sh
RUN chmod ug+x /opt/hcf/post-start.sh

# Install configgin
ADD configgin /opt/hcf/configgin/

# Add rsyslog configuration
ADD rsyslog_conf/etc /etc/

# Fix monit's logrotate config (created in the `apt-get install monit` above) to our new log file location
#RUN sed -i 's/log/vcap\/monit/' /etc/logrotate.d/monit

# Monit needs to reload after rotating logs, however, the default policy-rc.d in Ubuntu's docker image forbids it
# This default is in place due to errors when services try to restart during `docker build`
# See https://github.com/docker/docker/blob/243d4dcc7e9ea3eb665301d5e3756afa4adb04f7/contrib/mkimage/debootstrap#L43-L45
# It should not pose a problem at this point to re-allow service restarts
# TODO: Needed?
#RUN echo "#!/bin/sh\nexit 0" > /usr/sbin/policy-rc.d

# Make logrotate run hourly, not daily
RUN mv /etc/cron.daily/logrotate /etc/cron.hourly/logrotate
